import { defineConfig } from '@alova/wormhole'
import { stripOperationIdPrefix, stripTagPrefix, stripSchemaPrefix, requiredResponses, modelDefaults, customIndex } from './codegen/plugins'

// Swagger source: docs/swagger.json (generated by ./main.sh docs at repo root).
// This config is loaded with cwd = packages/apiclient, so paths are relative
// to this package.
const input = '../../../docs/swagger.json'

const includePaths = (prefixes: string[]) => (api: any) => {
  const url: string = api.url ?? api.path ?? ''
  return prefixes.some((p) => url.startsWith(p)) ? api : undefined
}

// Per-app wiring injected by `customIndex` into each generated lib/sdk/index.ts:
// toast/session handlers registered via Api.NewEvent, model overrides and
// re-exports. The runtime (alova instance, Api, Apis) is emitted by the plugin.
const usrWiring = `
import { toast } from 'vue-sonner'
import { ResetPasswordIn as GenResetPasswordIn } from './models'
import type { ResetPasswordIn as GenResetPasswordInT } from './models'

const retried = new Set<string>()

function ok(_response: Response, method: Method, data: unknown) {
  const t = useNuxtApp().$i18n.t
  if (method.type !== 'GET') toast.success(t('success'))
  return data
}

async function unauthorized(_response: Response, method: Method) {
  const auth = useAuthStore()
  if (method.meta?.isRefresh) {
    auth.$signOut()
    throw new Error('refresh failed')
  }
  const key = \`\${method.type}:\${method.url}:\${JSON.stringify(method.config.params ?? {})}\`
  if (retried.has(key)) {
    auth.$signOut()
    throw new Error('retry failed')
  }
  retried.add(key)
  if (await auth.$refresh()) {
    return method.send(true)
  }
  auth.$signOut()
  throw new Error('refresh failed')
}

function fallback(response: Response, _method: Method, v: unknown) {
  const t = useNuxtApp().$i18n.t
  if (v && typeof v === 'object') {
    const { code, message } = v as { code?: string; message?: string }
    if (code) toast.warning(t(code))
    else if (message) toast.error(message)
  }
  throw response.statusText
}

Api.NewEvent(200, ok)
Api.NewEvent(401, unauthorized)
Api.NewEvent(-1, fallback)

// ResetPasswordIn adds a client-only confirm field for the form.
export type ResetPasswordIn = GenResetPasswordInT & { confirm: string }
export const ResetPasswordIn: ResetPasswordIn = { ...GenResetPasswordIn, confirm: '' }

export { Auth, AuthIn, Profile, ProfileIn } from './models'
`

const admWiring = `
const retried = new Set<string>()

function ok(_response: Response, method: Method, data: unknown) {
  const t = useNuxtApp().$i18n.t
  if (method.type !== 'GET') {
    useSnackBar().success(t('success'))
  }
  return data
}

async function unauthorized(_response: Response, method: Method) {
  const auth = useAuthStore()
  if (method.meta?.isRefresh) {
    auth.$signOut()
    throw new Error('refresh failed')
  }
  const key = \`\${method.type}:\${method.url}:\${JSON.stringify(method.config.params ?? {})}\`
  if (retried.has(key)) {
    auth.$signOut()
    throw new Error('retry failed')
  }
  retried.add(key)
  if (await auth.$refresh()) {
    return method.send(true)
  }
  auth.$signOut()
  throw new Error('refresh failed')
}

function fallback(response: Response, _method: Method, v: unknown) {
  const t = useNuxtApp().$i18n.t
  if (v && typeof v === 'object') {
    const { code, message } = v as { code?: string; message?: string }
    if (code) {
      useSnackBar().warn(t(code))
    } else if (message) {
      useSnackBar().warn(message)
    }
  }
  throw response.statusText
}

Api.NewEvent(200, ok)
Api.NewEvent(401, unauthorized)
Api.NewEvent(-1, fallback)

export * from './models'
`

export default defineConfig({
  generator: [
    // ── User app: usr + public (std) ───────────────────────────────────
    {
      input,
      output: '../../apps/usr/app/lib/sdk',
      type: 'ts',
      global: 'Apis',
      // filter to usr and std routes only (point 4)
      handleApi: includePaths(['/usr/api/v1', '/api/v1']),
      plugins: [
        stripOperationIdPrefix('usr'),
        stripTagPrefix('usr'),
        // restore clean model names (UsrAuth -> Auth, ...); global shared
        // models like BaseQueries / db.User stay unprefixed and untouched.
        stripSchemaPrefix('Usr'),
        requiredResponses(['/usr/api/v1', '/api/v1']),
        modelDefaults('../../apps/usr/app/lib/sdk', ['/usr/api/v1', '/api/v1']),
        customIndex(usrWiring, 'useAuthStore'),
      ],
    },
    // ── Admin app: adm + public (std) ──────────────────────────────────
    {
      input,
      output: '../../apps/adm/app/lib/sdk',
      type: 'ts',
      global: 'AdmApis',
      // filter to adm and std routes only (point 4)
      handleApi: includePaths(['/adm/api/v1', '/api/v1']),
      plugins: [
        stripOperationIdPrefix('adm'),
        stripTagPrefix('adm'),
        stripSchemaPrefix('Adm'),
        requiredResponses(['/adm/api/v1', '/api/v1']),
        modelDefaults('../../apps/adm/app/lib/sdk', ['/adm/api/v1', '/api/v1']),
        customIndex(admWiring, 'useAuthStore'),
      ],
    },
  ],
})
