import { defineConfig } from '@alova/wormhole'
import {
  stripOperationIdPrefix,
  stripTagPrefix,
  stripSchemaPrefix,
  requiredResponses,
  modelDefaults,
  customIndex,
} from './codegen/plugins'

// Swagger source: docs/swagger.json (generated by ./main.sh docs at repo root).
// This config is loaded with cwd = packages/apiclient, so paths are relative
// to this package.
const input = '../../../docs/swagger.json'

const includePaths = (prefixes: string[]) => (api: any) => {
  const url: string = api.url ?? api.path ?? ''
  return prefixes.some((p) => url.startsWith(p)) ? api : undefined
}

export default defineConfig({
  generator: [
    // ── User app: usr + public (std) ───────────────────────────────────
    {
      input,
      output: '../../apps/usr/app/lib/sdk/gen',
      type: 'ts',
      global: 'Apis',
      // filter to usr and std routes only (point 4)
      handleApi: includePaths(['/usr/api/v1', '/api/v1']),
      plugins: [
        stripOperationIdPrefix('usr'),
        stripTagPrefix('usr'),
        // restore clean model names (UsrAuth -> Auth, ...); global shared
        // models like BaseQueries / db.User stay unprefixed and untouched.
        stripSchemaPrefix('Usr'),
        requiredResponses(['/usr/api/v1', '/api/v1']),
        modelDefaults('../../apps/usr/app/lib/sdk/gen', ['/usr/api/v1', '/api/v1']),
        customIndex(),
      ],
    },
    // ── Admin app: adm + public (std) ──────────────────────────────────
    {
      input,
      output: '../../apps/adm/app/lib/sdk/gen',
      type: 'ts',
      global: 'AdmApis',
      // filter to adm and std routes only (point 4)
      handleApi: includePaths(['/adm/api/v1', '/api/v1']),
      plugins: [
        stripOperationIdPrefix('adm'),
        stripTagPrefix('adm'),
        stripSchemaPrefix('Adm'),
        requiredResponses(['/adm/api/v1', '/api/v1']),
        modelDefaults('../../apps/adm/app/lib/sdk/gen', ['/adm/api/v1', '/api/v1']),
        customIndex(),
      ],
    },
  ],
})
