definitions:
  AdmAdminIn:
    properties:
      password:
        maxLength: 20
        minLength: 4
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  AdmAdminsPage:
    properties:
      content:
        items:
          $ref: '#/definitions/Admin'
        type: array
      page:
        type: integer
      total:
        type: integer
    type: object
  AdmAuth:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  AdmAuthIn:
    properties:
      password:
        maxLength: 20
        minLength: 4
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  AdmProfileIn:
    properties:
      username:
        type: string
    required:
    - username
    type: object
  AdmResetPasswordIn:
    properties:
      new:
        maxLength: 50
        minLength: 4
        type: string
      old:
        maxLength: 50
        minLength: 4
        type: string
    required:
    - new
    - old
    type: object
  AdmStats:
    properties:
      admins:
        type: integer
      users:
        type: integer
    type: object
  AdmUserIn:
    properties:
      password:
        maxLength: 20
        minLength: 4
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  AdmUsersPage:
    properties:
      content:
        items:
          $ref: '#/definitions/User'
        type: array
      page:
        type: integer
      total:
        type: integer
    type: object
  Admin:
    properties:
      created_at:
        type: string
      id:
        type: integer
      password:
        description: Password
        type: string
      updated_at:
        type: string
      username:
        description: Username
        type: string
    type: object
  Fail:
    properties:
      code:
        description: Application-specific error code
        type: string
      message:
        description: Human-readable error message
        type: string
      system:
        description: Raw system error (only shown in debug mode)
    type: object
  User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      password:
        description: Password
        type: string
      updated_at:
        type: string
      username:
        description: Username
        type: string
    type: object
  UsrAuth:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  UsrAuthIn:
    properties:
      password:
        maxLength: 20
        minLength: 4
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  UsrResetPasswordIn:
    properties:
      new:
        maxLength: 50
        minLength: 4
        type: string
      old:
        maxLength: 50
        minLength: 4
        type: string
    required:
    - new
    - old
    type: object
  UsrUser:
    properties:
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  UsrUserIn:
    properties:
      username:
        minLength: 4
        type: string
    required:
    - username
    type: object
info:
  contact: {}
  description: API Documentation
  title: webtplmst
  version: "1.0"
paths:
  /adm/api/v1/admin:
    get:
      consumes:
      - application/json
      operationId: admListAdmins
      parameters:
      - in: query
        name: column
        type: string
      - in: query
        name: desc
        type: boolean
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AdmAdminsPage'
      security:
      - ApiKeyAuth: []
      summary: List Admins
      tags:
      - admAdmin
    post:
      consumes:
      - application/json
      operationId: admCreateAdmin
      parameters:
      - description: Admin object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmAdminIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Admin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Create Admin
      tags:
      - admAdmin
  /adm/api/v1/admin/{id}:
    delete:
      consumes:
      - application/json
      operationId: admDeleteAdmin
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Remove Admin
      tags:
      - admAdmin
    get:
      consumes:
      - application/json
      operationId: admFindAdmin
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Admin'
      security:
      - ApiKeyAuth: []
      summary: Find Admin by ID
      tags:
      - admAdmin
    put:
      consumes:
      - application/json
      operationId: admUpdateAdmin
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      - description: Admin object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmAdminIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Update Admin
      tags:
      - admAdmin
  /adm/api/v1/admin/password:
    put:
      consumes:
      - application/json
      operationId: admResetPassword
      parameters:
      - description: Password object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmResetPasswordIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Reset current admin password
      tags:
      - admAdmin
  /adm/api/v1/admin/profile:
    put:
      consumes:
      - application/json
      operationId: admUpdateProfile
      parameters:
      - description: Profile object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmProfileIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Update current admin profile
      tags:
      - admAdmin
  /adm/api/v1/auth/in:
    post:
      consumes:
      - application/json
      description: Sign in with username and password
      operationId: admSignIn
      parameters:
      - description: Credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmAuthIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AdmAuth'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      summary: Admin sign in
      tags:
      - admAuth
  /adm/api/v1/stat:
    get:
      consumes:
      - application/json
      operationId: admGetStats
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AdmStats'
      security:
      - ApiKeyAuth: []
      summary: Get system stats
      tags:
      - admAdmin
  /adm/api/v1/user:
    get:
      consumes:
      - application/json
      operationId: admListUsers
      parameters:
      - in: query
        name: column
        type: string
      - in: query
        name: desc
        type: boolean
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AdmUsersPage'
      security:
      - ApiKeyAuth: []
      summary: List Users
      tags:
      - admUser
    post:
      consumes:
      - application/json
      operationId: admCreateUser
      parameters:
      - description: User object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmUserIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Create User
      tags:
      - admUser
  /adm/api/v1/user/{id}:
    delete:
      consumes:
      - application/json
      operationId: admDeleteUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Remove User
      tags:
      - admUser
    get:
      consumes:
      - application/json
      operationId: admFindUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
      security:
      - ApiKeyAuth: []
      summary: Find User by ID
      tags:
      - admUser
    put:
      consumes:
      - application/json
      operationId: admUpdateUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/AdmUserIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - admUser
  /api/v1/rate/{code}:
    get:
      consumes:
      - application/json
      description: Get exchange rates by currency code
      operationId: findRate
      parameters:
      - description: Currency code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
      summary: Get exchange rates
      tags:
      - Rate
  /usr/api/v1/auth/in:
    post:
      consumes:
      - application/json
      description: Sign in with username and password
      operationId: usrSignIn
      parameters:
      - description: Credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UsrAuthIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UsrAuth'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      summary: User sign in
      tags:
      - usrAuth
  /usr/api/v1/user:
    get:
      consumes:
      - application/json
      operationId: usrFindUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UsrUser'
      security:
      - ApiKeyAuth: []
      summary: Find User by ID
      tags:
      - usrUser
    put:
      consumes:
      - application/json
      operationId: usrUpdateUser
      parameters:
      - description: User object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UsrUserIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Update User
      tags:
      - usrUser
  /usr/api/v1/user/reset/password:
    post:
      consumes:
      - application/json
      description: Reset current user's password
      operationId: usrResetPassword
      parameters:
      - description: Password object
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UsrResetPasswordIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Fail'
      security:
      - ApiKeyAuth: []
      summary: Reset user password
      tags:
      - usrUser
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
